[[servers]]
protocol="http"                        # 定义协议，采用http方式， 支持协议有：http，https, fcgi_unix ,rpc_unix ,rpc_tcp ,rpc_tcp_ssl
                                       # 其中fcgi_unix是指：fcgi UnixDomainSocket ,rpc_unix是指：rpc方式的 UnixDomainSocket
addr=""                                # 定义地址, 如果protocol="unix"，那么addr就需要设置为xxxx.sock的文件地址，例如： "/tmp/alphabetsample.sock"
                                       # 支持 ${project} 变量，表示项目根目录
                                       #   addr="${project}/alphabetsample.sock"
port=10060                              # 定义端口
timeout=10                             # 超时时长，单位秒
maxconn=100                            # 最大连接数，暂时不支持

[[web]]
context="sysconfigservice"            # 定义web访问根路径
apps="*"                             # 是否过滤应用包
mode="develop"                       # develop 是开发者模式， product 是生产模式，
                                     # 如果设置 develop模式可以查看pprof信息：http://ip:port/debug/pprof
                                     # 也可以通过命令查看：go tool pprof -text http://ip:port/debug/pprof/heap
i18n="en"                            # 设置缺省的国际化信息，如果定义 i18n="en" ，那么就会查找 /apps/app**/i18n/en.toml内容
sessionid="alphabet-sysconfig-session-id"    # 设置sessionid 信息
sessionmaxage=600                    # 设置session失效日期，单位是秒
sessionobjectcount=10000             # 设置session可以存储的对象数，超过该对象，就会启动清理 ，一个对象就是一个session会话
sessiongenkey="dA~$%3@2*sAw  (:sQQ"  # 设置session产生key，用于加密
sessionstore="memory"                # session存储方式，支持 memory 和 redis 两种
sessionstorename="cache2"            # 设置session存储库的名称，
                                     # 如果是redis方式，那么就是设置cachesconfig.toml的某个库；
                                     # 如果是memory方式，那么就设置""。
                                     # 如果没有设置，那么默认是memory方式。

[[uploadfile]]
memcachesize=8388608                 # 文件在读取过程中的缓存大小,单位字节，在一定范围内越大，读写速度越快
maxsize=33554432                     # 文件大小,单位字节
storepath="${project}/upload"        # 文件上传的存储地址,其中 ${project} 表示项目根目录，例如：${project}/upload
splitonapps=true                     # 是否按照应用（apps）分目录

[[project]]
cpunum=3                             # 设置CPU使用个数

[[pprof]]
clientIP=["*"]                       # 客户端可访问的ip地址，可以是数组
username="user1"                     # 用户名 , 传递参数 username=user1&password=123456
password="123456"                    # 密码
